/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package misa.xform.model.Extract.validation;

import misa.xform.model.Extract.Description;

/**
 * A sample validator interface for {@link misa.xform.model.Extract.AttributeDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeDefValidator {
	boolean validate();

	boolean validateDescription(Description value);
	boolean validateName(String value);
	boolean validateTypeName(String value);
}
