/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package misa.xform.model.Extract.validation;

import misa.xform.model.Extract.ClassDef;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link misa.xform.model.Extract.Root}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RootValidator {
	boolean validate();

	boolean validateClassDef(EList<ClassDef> value);
	boolean validateTargetProject(String value);
}
